image: ruby:2.6.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install bundler:2.1.4
          - bundler --version
          - bundle install
          - JEKYLL_ENV=production bundle exec jekyll build -t  --config _config.yml -d _site/aireidentity-doc
          - bundle exec htmlproofer ./_site --url-ignore "/#.*/,/http://.*/,/https://.*/"
  branches:
    master:
      - step:
          script:
            - gem install bundler:2.1.4
            - bundler --version
            - bundle install
            - JEKYLL_ENV=production bundle exec jekyll build -t  --config _config.yml
            # - bundle exec htmlproofer ./_site --url-ignore "/#.*/,/http://.*/,/https://.*/"
            - git clone https://github.com/airelogic/aireidentity-doc.git
            - cp -r /opt/atlassian/pipelines/agent/build/_site/* aireidentity-doc/
            - cd aireidentity-doc
            - git config --global user.email "product.operations@airelogic.com"
            - git config --global user.name "Aire Innovate"
            - git config --global push.default simple
            - git add --all
            - git commit -m "Website auto build on `date`"
            - git push https://$githubtoken@github.com/airelogic/aireidentity-doc.git

definitions:
  caches:
    bundler: ./vendor
